service: websocket-serverless-nestjs

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  websocketApiName: websocket-nest-${self:provider.stage}
  websocketApiRouteSelectionExpression: $request.body.action

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - nodemon.json
    - README.md

functions:
  websocketNest:
    handler: dist/main.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket: 
          route: $default
      # - websocket:
      #     route: broadcast
      # - websocket: 
      #     route: $default
      # - http:
      #     cors: true
      #     path: '/'
      #     method: any
      # - http:
      #     cors: true
      #     path: '{proxy+}'
      #     method: any
      - http: ANY /
      - http: 'ANY {proxy+}'
